apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-certificate
  namespace: argocd
spec:
  secretName: example-tls-secret
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  commonName: example.com
  dnsNames:
    - example.com
